### ISSUE TITLE
[FEATURE_REQUEST]: Expliquer l'univers du RPG

### ISSUE THREAD

**Issue by Pavlos93** [Nyfos/KoroiBotCommunity#10]
**Votre demande de fonctionnalité est-elle liée à un problème? Soyez précis.**
> Une petite commande expliquant l'univers du RPG pour mieux comprendre les éléments de celui-ci et éviter certaines confusion *(qu'est ce qu'un recho et les nyutos, etc)*.

**Décrivez la solution que vous aimeriez avoir**
> Une petite commande expliquant ce que sont les Recho, à quoi servent ils, etc... Car à mes débuts sur le RPG, je ne comprenais pas vraiment si c'était des minerais des animaux ou des plantes ^^'
> C'est peut être l'une des commandes les plus embêtantes à réaliser, mais elle serait pratique pour la compréhension du RPG.

**Décrivez les alternatives que vous avez envisagées**
> Ou alors, aux commandes `K!rechos`, `K!nyutos`, etc, mettre dans un *"coin"* de l'embed quelques explications à leur propos.

**Informations supplémentaires**
/

**Comment by Nyfos** [comment]
Que penseriez-vous d'un message qui s'afficherait lorsqu'un utilisateur rejoint le RPG, expliquant tout ceci ?
Cette commande pourrait raconter l'"histoire" du RPG, ce que sont les rechos, faire quelque chose d'assez RP et avec des petites références au RPG ? "Autrefois", "Depuis ce jour", "Aidez-nous..." Cette commande pourra également "aguicher" les joueurs.

Voici une concrétisation de ma proposition :

> "**_Au cours de votre aventure, vous laisserez votre trace sur le RPG, partirez à la conquête de nombreux animaux appelés rechos, devrez vous battre pour survivre, entretenir vos cultures, et même tenter de devenir le premier joueur du RPG ! Attention cependant, de nombreux obstacles se dresseront sur votre chemin, et ce sera une quête très ardue. Seuls les meilleurs pourront se faire une place dans cet univers hors du commun !_**"

**Comment by Pavlos93** [comment]
Ça me paraît être la solution la plus efficace, même plus qu'une commande qui prendra de la place. Je suis pour !

**Comment by Nyfos** [comment]
Nous partons pour ceci alors.

**Comment by Nyfos** [comment]
Le message a été rédigé et sera affiché lors de la prochaine mise à jour du RPG.
