### ISSUE TITLE
[FEATURE_REQUEST]: Idées de nouvelles zones RPG

### ISSUE THREAD

**Issue by liloo81** [Nyfos/KoroiBotCommunity#12]
**Votre demande de fonctionnalité est-elle liée à un problème? Soyez précis.**
Une description claire et concise du problème. Ex. Je suis toujours frustré quand [...]

**Décrivez la solution que vous aimeriez avoir**
Une description claire et concise de ce que vous voulez faire.

**Décrivez les alternatives que vous avez envisagées**
Une description claire et concise de toutes les solutions ou fonctionnalités alternatives que vous avez envisagées.

**Informations supplémentaires**
Ajoutez n'importe quelle autre information concernant la fonctionnalité ici

**Comment by liloo81** [comment]
Petite idee pour la zone apres le Volcan je propose un lac avec des recho aquatique et tout

**Comment by Nyfos** [comment]
Ta suggestion est très similaire à d'autres zones déjà présentes, et tu as déjà insinué quelque chose de similaire dans une autre demande. Merci d'être compréhensif, ta suggestion reste enregistrée et pourra nous aider pour plus tard.
