### ISSUE TITLE
[RPG_FEATURE_REQUEST]: Laboratoire

### ISSUE THREAD

**Issue by liloo81** [Nyfos/KoroiBotCommunity#17]
4) Laboratoire 
-Pouvoir extraire l'ame d'un recho et la fusionner avec une autre ame pour faire un recho fusionner
-Améliorer les composant pour drone 
-avoir un robot que combat qui nous aides dans les combat 
Les drones et le robot peuvent monter jusqu'au niveau 5 le robot peut etre equiper d'armure et arme 
Pouvoir reparer les disfonctionement dans les drones quand ils travaillent trop

**Comment by Nyfos** [comment]
Je penserais plus à des ADNs de rechos plutôt que des âmes... Sinon, le reste à l'air intéressant, ce sera sûrement développé. J'adore l'idée des dysfonctionnement de drones.
=
