### ISSUE TITLE
[FEATURE_REQUEST]: '/userinfo | ADMINISTRATOR'

### ISSUE THREAD

**Issue by volcanofr** [Nyfos/KoroiBotCommunity#24]
__**Commande `/userinfo`**__
**Votre demande de fonctionnalité est-elle liée à un problème? Soyez précis.**
Un embed grand prend de la place dans le chat, ne permettant pas de tout voir d'un coup d'œil sur téléphone par exemple.

**Décrivez la solution que vous aimeriez avoir**
Baisser le nombre de permissions visible, surtout avec les personnes ayant la permission administrateur.

**Décrivez les alternatives que vous avez envisagées**
si la permission Administrateur est détectée, ne mettre que cette permission visible avec un explicatif qui dit que la permission admin donne toutes les autres

**Informations supplémentaires**
N/A

**Comment by Nyfos** [comment]
Merci beaucoup de prendre le temps de publier une suggestion.
J'ai trouvé ta proposition très intéressante et utile; elle a été ajoutée au bot.
Encore merci de participer à la vie du bot!
