### ISSUE TITLE
[FEATURE_REQUEST]: '/logs config | all in one'

### ISSUE THREAD

**Issue by volcanofr** [Nyfos/KoroiBotCommunity#25]
__**Avec la commande `/logs config`**__
**Votre demande de fonctionnalité est-elle liée à un problème? Soyez précis.**
Il est long pour l'administrateur de faire la commande événement par événement...

**Décrivez la solution que vous aimeriez avoir**
Mettre une commande pour activer / désactiver tous les évènements d'un coup

**Informations supplémentaires**
N/A

**Comment by Nyfos** [comment]
Ta suggestion a été ajoutée au bot; tu peux désormais utiliser la commande `/toggleall <on|off>`.
Merci beaucoup!
