### ISSUE TITLE
[FEATURE_REQUEST]: 'Faire fonctionner /userinfo pour les bots'

### ISSUE THREAD

**Issue by Owlainerz** [Nyfos/KoroiBotCommunity#26]
**Votre demande de fonctionnalité est-elle liée à un problème? Soyez précis.**
La commande `/userinfo` ne permet pas d'afficher le profil des bots.

**Décrivez la solution que vous aimeriez avoir**
Selon moi, il faudrait que la commande fonctionne aussi pour les bots pour obtenir des informations sur eux.

**Décrivez les alternatives que vous avez envisagées**
N/C

**Informations supplémentaires**
N/C

**Comment by Nyfos** [comment]
La commande `/userinfo` permet déjà d'afficher le profil des bots.
