### ISSUE TITLE
[SERVER_REQUEST]: 'Déplacement salon FAQ'

### ISSUE THREAD

**Issue by volcanofr** [Nyfos/KoroiBotCommunity#30]
Déplacer le salon _#📚・faq-koroimod_, qui est actuellement dans la catégorie _📰┆Informations_, dans la catégorie _📞┆Support_.

Je voudrais que le serveur entreprenne ce changement car les personnes ayant des questions ne regardent pas forcément toute la liste des salons et vont directement voir le _@Support_.

**Comment by Nyfos** [comment]
Un bot dédié sera utilisé pour le support. Si un article est trouvé dans la FAQ, il sera communiqué à l'utilisateur avant même qu'il ne puisse envoyer sa demande. Pour cette raison, j'ai pris la décision de laisser la FAQ à son emplacement actuel. Merci tout de même pour ta suggestion très intéressante!
