### ISSUE TITLE
Une commande d’infos de l’utilisateur 

### ISSUE THREAD

**Issue by thekingofkillers1** [Nyfos/KoroiBotCommunity#37]
### Pour quel(s) bot(s) cette demande de fonctionnalité est-elle destinée?

KoroïMod

### Fonctionnalité

On pourrait faire une commande qui permettrai de voir les "logs" d’une personne avec ses warns, ses kicks et ses bans. Certains bots comme MEE6 se réinitialisent quand la personne quitte le serveur. Je propose donc que les infos soient stockées et consultables sur tous les serveurs où est la personne : je m’explique, si la dite personne s’est faite ban d’un serveur il sera possible de voir ce ban sur un autre serveur, peu importe le membre du staff qui le demande, c’est un peu comme des logs en commun. Il faudrait aussi faire une historique des messages envoyés (si la personne supprime un message à contenu disont "embarrassant" on pourrait le voir et faire une sanction appropriée.

### Solution ou implémentation idéale

Une commande style !userinfo [le nom] {here} (pour le serveur où a été faite la commande) et une autre style : !userinfo [le nom] {total} (pour tous les serveurs au total) et une autre !userinfo [le nom] {le nom du serveur (une liste pourrait être proposée)} (pour connaître les infos de la personne sur le serveur)

**Comment by Nyfos** [comment]
Merci beaucoup pour ta suggestion @thekingofkillers1! 🙏🏽

Ta première suggestion, à propos de logs en commun, est très intéressante. En revanche, la seconde, qui parle d'une fonctionnalité de logs de messages, est inutile, car déjà présente: on peut activer les logs de messages supprimés pour envoyer ceux-ci dans un salon du serveur.

Concernant l'implémentation, je te propose plutôt cette unique commande slash:
`/infractions <utilisateur> <Infractions sur ce serveur|Infractions sur tous les serveurs où le bot est présent>`
(rien ne garanti que la commande sera nommée ainsi, ce n'est qu'un exemple)

Pour finir, je n'ajouterai pas de fonctionnalité pour obtenir les logs sur un serveur en particulier. Avec cette fonctionnalité, des personnes malveillantes pourraient inclure de la publicité, des liens malveillants, etc. dans le nom de leur serveur.

**Comment by Nyfos** [comment]
Une commande `/infractions` a été implémentée. Malheureusement, cette commande n'affiche que les infractions sur le serveur où elle est utilisée.

Si ta proposition de "logs en commun", bien qu'intéressante, n'a pas été implémentée, c'est parce qu'elle aurait été trop peu fiable. Il n'y aurait eu aucune preuve de chaque infraction. Ainsi, n'importe qui aurait pu donner 150 avertissements à un utilisateur dans le seul but que ceux-ci soient affichés partout. Même en affichant la raison de l'avertissement, il n'y aurait aucun moyen d'obtenir une preuve de l'infraction. Pour résumer, elle n'a pas été implémentée pour éviter que des utilisateurs soient mis de côté ou sanctionnés sans raison valable.
