### ISSUE TITLE
Suppression automatique des insultes

### ISSUE THREAD

**Issue by JustOwlainers** [Nyfos/KoroiBotCommunity#39]
### Pour quel(s) bot(s) cette demande de fonctionnalité est-elle destinée?

KoroïMod

### Fonctionnalité

Une personne insulte, c'est énervant non ? Pourquoi pas une suppression automatique d'une insulte, d'un lien ou autre

### Solution ou implémentation idéale

Une suppression automatique d'une insulte renverrait un message (voir schéma) et supprimerait son message. Une fois supprimer, nous pourrions voir dans les logs un message qui a été supprimé.
![Exemple](https://user-images.githubusercontent.com/74816036/170719976-4ab5d411-c83e-46dd-9a5a-ab9920c2ba18.png)

**Comment by Nyfos** [comment]
La suggestion est très intéressante, mais le filtre contre les grossièretés a été désactivé pour le moment, car le premier prototype de ce système a mal été conçu. Le bot détectait trop de mots (**com**portement par exemple), et devait connaître tous les mots de la langue française. De plus, il n'était pas compatible avec les autres langues, ce qui était une très grosse faiblesse.
La seule alternative que j'ai trouvé pour le moment serait de réduire la capacité d'analyse du filtre pour permettre une sélection plus affinée, mais plus facilement contournable.

En attendant la ré-implémentation du filtre, ta demande est marquée comme "Non prévue". Je la réouvrirai lorsque je réimplémenterai ce système.

**Comment by JustOwlainers** [comment]
D'accord cela me va.
