### ISSUE TITLE
Choix Autorole

### ISSUE THREAD

**Issue by JustOwlainers** [Nyfos/KoroiBotCommunity#41]
### Pour quel(s) bot(s) cette demande de fonctionnalité est-elle destinée?

KoroïMod

### Fonctionnalité

Nous devrions pouvoir mettre jusqu'à 20 réactions pour choisir 20 rôles sur l'autorole de KoroïMod.

### Solution ou implémentation idéale

Il faudrait ajouter cela à l'autorole pour permettre d'avoir plus de choix cela pourrais se présenter comme ceci :
![Exemple](https://user-images.githubusercontent.com/74816036/170744912-c7938b43-783b-42f2-a676-ed57954eaebe.png)

**Comment by Nyfos** [comment]
Nous ne prévoyons pas d'ajouter cette fonctionnalité pour le moment. Cependant, nous l'ajouterons si d'autres membres le demandent.
