### ISSUE TITLE
Problèmes de sécurité dans l'autorole

### ISSUE THREAD

**Issue by thekingofkillers1** [Nyfos/KoroiBotCommunity#42]
### Bot(s) concerné(s) par le bug

KoroïMod

### Partie(s) du bot concernée(s) par le bug

Les commandes slash

### Description du problème

C’est un bug avec l’autorole. Actuellement je peux faire un autorole avec un rôle supérieur au mien (par exemple je peux en créer un avec le rôle fondateur)
![2FDC98E2-CD51-4B4D-8ED2-5EDC80F689CD](https://user-images.githubusercontent.com/106347248/170830877-f275cdd1-8a81-4061-a036-7caaad9882a1.png)

### Version web de Discord

- [ ] J'utilise la version web de Discord

### Priorité du problème

Problème de sécurité (sécurité compromise, doit être corrigé immédiatement)

### J'ai testé ce problème sur une version de développement (alpha ou beta)

a.23414b0

**Comment by Nyfos** [comment]
Corrigé dans la version `a.0ee97d7.c28355e35d8619ed0b437f5484d301ea7`.
