### ISSUE TITLE
[FEATURE_REQUEST]: Ajout d'une fonctionnalité de musique

### ISSUE THREAD

**Issue by thekingofkillers** [Nyfos/KoroiBotCommunity#6]
**Votre demande de fonctionnalité est-elle liée à un problème? Soyez précis.**
Une description claire et concise du problème. Ex. Je suis toujours frustré quand [...]

**Décrivez la solution que vous aimeriez avoir**
Une description claire et concise de ce que vous voulez faire.

**Décrivez les alternatives que vous avez envisagées**
Une description claire et concise de toutes les solutions ou fonctionnalités alternatives que vous avez envisagées.

**Informations supplémentaires**
Ajoutez n'importe quelle autre information concernant la fonctionnalité ici

**Comment by thekingofkillers** [comment]
Ajouter une fonctionnalité musique

**Comment by Nyfos** [comment]
@thekingofkillers cette fonctionnalité était déjà prête pour la fonctionnalité d'aujourd'hui, en honneur à l'anniversaire de KoroïBot, mais malheureusement, je devrais refaire le système..

**Comment by Nyfos** [comment]
Je garde votre demande ouverte :)
