### ISSUE TITLE
[FEATURE_REQUEST]: Clarifier certaines choses: Pavlos#6829

### ISSUE THREAD

**Issue by Pavlos93** [Nyfos/KoroiBotCommunity#8]
**Votre demande de fonctionnalité est-elle liée à un problème? Soyez précis.**
> Je remarque que la prise en main avec le RPG est assez complexe. Je trouve que il serait bien de simplifier quelques petites choses.

**Décrivez la solution que vous aimeriez avoir**
> Je trouverais cela plus pratique de réunir toutes les nourritures, Nyuto, recho, etc... dans le même embed (`K!inv`). Cela réduirait le nombre de commande pour éviter de ne pas s'y retrouver. Ça serait beaucoup plus pratique pour faire des actions plus rapidement comme par exemple avoir un visuel sur tous nos recho et nourriture dans un seul embed pour pouvoir les nourrir.).
> Il serait pratique d'avoir une commande `K!didactitiel` qui nous explique le fonctionnement du RPG, ce que son les recho, comment avoir de l'argent, etc... *(une vidéo YouTube serait génial)*.

**Décrivez les alternatives que vous avez envisagées**
> Supprimer les commande `K!rechos`, `K!nourriture`, etc... pour tout rassembler dans la commande `K!inv`
> Une commande `K!didactitiel` qui nous demandera dans un premier temps de par exemple d'exécuter la commande `K!hunt` lorsque nous aurons changés de zone avec la commande `K!zone`, nourrir notre butin de la chasse (`K!hunt`) avec `K!feed`, etc...
> À chaque objectif du didacticiel passé, nous pourrions recevoir de l'argent pour bien débuter l'aventure. 

**Informations supplémentaires**
> Cette fois-ci, ce sera à propos des suggestions. Il serait pratique que chaque suggestion faites sur GitHub soient envoyées dans un salon suggestion où les membres du serveur pourraient réagir avec des réaction pour exprimer leur accord ou leur désaccord avec la suggestion.

**Comment by Nyfos** [comment]
Très bonne idée, j'ajoute ça à la liste !
Merci beaucoup :)

**Comment by Pavlos93** [comment]
Pas de soucis ;)

**Comment by Nyfos** [comment]
La commande `K!didactitiel` est achevée et appliquée.
Je viens de m'aperçevoir qu'il y avait une partie consacrée à GitHub, j'aime vraiment l'idée, je vais voir ce que je peux faire :)

**Comment by Nyfos** [comment]
Tout a été ajouté au RPG. Merci beaucoup pour ta suggestion concise et détaillée, cela nous aide infiniment !
