### ISSUE TITLE
[FEATURE_REQUEST]: Afficher la zone courante dans l'embed des zones

### ISSUE THREAD

**Issue by Pavlos93** [Nyfos/KoroiBotCommunity#9]
**Petite suggestion:** dans la commande `K!zone` pouvoir voir dans l'embed dans quel zone nous somme actuellement.

**Comment by Nyfos** [comment]
La fonctionnalité ne devait pas être implémentée, mais une mise à jour récente a corrigé quelque chose avec les zones. Nous pouvons donc implémenter votre demande.

**Comment by Nyfos** [comment]
Cette "issue" est épinglée en raison de multiples confusions suite à cette mise à jour, principalement car certains utilisateurs pensaient qu'ils ne se trouvaient dans aucune zone.
